---
- hosts: "all"

  pre_tasks:

    # Verify that you atom_user equals "vagrant" early in the process
    - name: "Make sure that you are not using www-data"
      fail:
        msg: "Wrong user"
      when: "atom_user == 'www-data'"

    # I can't think of a reason why I need this now but if I don't, ansible
    # will break when I try to compile the ArchivesCanada plugin, :(
    - lineinfile:
        dest: "/etc/sudoers"
        state: "present"
        validate: "visudo -cf %s"
        regexp: "^vagrant"
        line: "vagrant ALL=(ALL) ALL"
      become: "yes"

  roles:

    - role: "artefactual.elasticsearch"
      become: "yes"
      tags:
        - "elasticsearch"

    - role: "artefactual.percona"
      become: "yes"
      tags:
        - "percona"

    - role: "artefactual.percona-client"
      become: "yes"
      tags:
        - "percona-client"

    - role: "artefactual.memcached"
      become: "yes"
      tags:
        - "memcached"

    - role: "artefactual.gearman"
      become: "yes"
      tags:
        - "gearman"

    - role: "artefactual.nginx"
      become: "yes"
      tags:
        - "nginx"

    - role: "artefactual.atom"
      become: "yes"
      tags:
        - "atom"
